[tool.poetry]
name = "utils"
version = "0.1.0"
description = "my awesome python utils"
authors = ["CoodingPenguin <coodingpenguin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
